name: CI

on: [pull_request, push]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  style:
    name: Check basic style
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./.github/check-basic-style.sh

  check:
    name: 'Build & test'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - run: cargo build
    - run: cargo test
    - run: cargo doc

    - run: cargo build --features="derive serde"
    - run: cargo test --features="derive serde"
    - run: cargo doc --features="derive serde"

    - run: rustup target add thumbv7em-none-eabi
    - run: cargo build --target=thumbv7em-none-eabi
